import dynamic from "next/dynamic";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const HomePage = dynamic(() => import("../src/HomePage"), {
  ssr: false,
  loading: () => <div className="h-[72px] bg-orange" />,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
